slack:
  uris:
    conversations:
      create: /conversations.create
      invite: /conversations.invite
      list: /conversations.list

    messages:
      post-message: /chat.postMessage
    files:
      upload: /files.upload

