spring:
  application:
    name: slack-adapter

  profiles:
    active: dev
    group:
      default:
        - uris
        - channels
        - informations
      dev:
        - authorization-dev
      prod:
        - authorization-prod
